# Dependencies
kramdown:
  input: GFM
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            "Robotics: Science and Systems"
tagline:          'A Robotics Conference'
description:      'June 27th - July 1st, 2022.'
url:              "https://roboticsconference.org"
baseurl:          ""
include:          ['_pages']
exclude:          ['README.md', 'LICENSE.md', 'Gemfile', 'Gemfile.lock', '.travis.yml', 'vendor', 'GRTAGS', 'GPATH', 'GTAGS', 'deploy.sh']

author:
  name:           'Yuke Zhu'
  url:            https://www.cs.utexas.edu/~yukez/

gems:             [jekyll-paginate]
paginate:         5
paginate_path:    "blog/page:num"

# Custom vars
version:          2.1.0

github:
  repo:

collections:
    attending:
       output: true
       permalink: /attending/:path/
       priority: 1
    program:
       output: true
       permalink: /program/:path/
       priority: 2
    committees:
       output: true
       permalink: /committees/:path/
       priority: 3
    information:
       output: true
       permalink: /information/:path/
       priority: 4

defaults:
  -
    scope:
      path: ""
    values:
      priority: 0
